# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import sys
from source.server import getServerMessages, startServer
from source.client import getClientMessages, startClient
import time
import threading


class Ui_MainWindow(object):
    executed = False

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 729)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 40, 55, 16))
        self.label.setObjectName("label")
        self.server_button = QtWidgets.QPushButton(self.centralwidget)
        self.server_button.setGeometry(QtCore.QRect(150, 580, 93, 28))
        self.server_button.setObjectName("server_button")
        self.client_button = QtWidgets.QPushButton(self.centralwidget)
        self.client_button.setGeometry(QtCore.QRect(560, 580, 93, 28))
        self.client_button.setObjectName("client_button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(590, 40, 55, 16))
        self.label_2.setObjectName("label_2")
        self.server_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.server_text.setGeometry(QtCore.QRect(30, 70, 331, 491))
        self.server_text.setObjectName("server_text")
        self.client_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.client_text.setGeometry(QtCore.QRect(420, 70, 341, 491))
        self.client_text.setObjectName("client_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        threading.Thread(target=self.updateUI, args=(), daemon=True).start()
        threading.Thread(target=startServer, args=(), daemon=True).start()
        threading.Thread(target=startClient, args=(), daemon=True).start()
        self.executed = True

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Server"))
        self.server_button.setText(_translate("MainWindow", "run server"))
        self.client_button.setText(_translate("MainWindow", "run client"))
        self.label_2.setText(_translate("MainWindow", "Client"))

    def updateUI(self):
        while self.executed == False:
            time.sleep(1)
            self.server_text.insertPlainText('\n'.join(getServerMessages()))
            self.client_text.insertPlainText('\n'.join(getClientMessages()))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
